### ISSUE TITLE
Running app tells me to "Build the demo"

### ISSUE THREAD

**Issue by AlexanderRies** [rjz/typescript-react-redux#40]
Hi,

I have just build the app with npm run build and started the app with npm run start.
The app tells that I have to runn the npm run build command again.
Is this a desired behaviour?

Best regards and thank you
Alex

**Comment by rjz** [comment]
Hey Alex, thanks for reporting this! It's definitely not desired behavior.

I've pushed a change (see #41) to fix the build. Take a peek when you have a moment, and please do circle back if you run into further issues!

Thanks again, and happy hacking—

**Comment by AlexanderRies** [comment]
Hi RJ,

thanks for the fix. Worked well.

Cheers from southern Germany

Alex
